### ISSUE TITLE
Having problems with golden lasso again, Version 1.12.2-1.22.1.7

### ISSUE THREAD

**Issue by crossfirearena** [TheRandomLabs/RandomPatches#130]
Looked at RandomPatches breaks ExtraUtils Golden Lasso #20 already.

Player uses lasso, it spawns the mob back in the original spot when it is placed instead of the spot it was placed at. It is repeatable.

**Comment by Nereithr** [comment]
> Looked at RandomPatches breaks ExtraUtils Golden Lasso #20 already.
> 
> Player uses lasso, it spawns the mob back in the original spot when it is placed instead of the spot it was placed at. It is repeatable.

I'm building a modpack, so I'm testing various perf mods for compatibility and this isn't a RandomPatches issue, Golden Lasso works just fine. This is caused by [the Surge mod](https://github.com/Epoxide-Software/Surge/issues/24), which implements the same MC-2025 fix, but doesn't include fixes for the issue that you describe. To fix this, go to surge.cfg and disable their MC-2025 fix. If you don't have Surge, some other mod includes that fix, so disable it from there.

**Comment by TheRandomLabs** [comment]
@crossfirearena can you confirm if this is the issue?

**Comment by crossfirearena** [comment]
> @crossfirearena can you confirm if this is the issue?

I havent had a chance to try this. I do have the surge mod on the server as it is a prebuilt pack, So that seems likely.

**Comment by TheRandomLabs** [comment]
Let me know if it wasn't Surge.
