### ISSUE TITLE
Information - What minor tweaks and do they affect performance?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheRandomLabs/RandomPatches#16]
I hate vague changelogs.

**Comment by TheRandomLabs** [comment]
They literally are very minor tweaks. I changed a few configuration property comments, moved a method to a different class so I could use it from another mod, and improved an error message. Sorry, I usually write more descriptive changelogs, but I thought it wouldn't matter in this case.
**EDIT:** Fixed in the CurseForge/versions.json changelogs.
