### ISSUE TITLE
Not intended behaviour in the EntityMixin#isInCauldronFilledWithWater()

### ISSUE THREAD

**Issue by ghost** [TheRandomLabs/RandomPatches#173]
Just letting you know, because my mod has the exactly same problem.

If an user has the mod in their client, they can use the Trident with Riptide inside a cauldron, even though the mod isn't installed on the server.

**Tested In:** Fabric Latest (2.1.8-fabric)

**Comment by TheRandomLabs** [comment]
Oh dear, thanks for letting me know! 😄

**Comment by TheRandomLabs** [comment]
As far as I can tell, fixing this issue would require the feature to be moved to another mod, as RandomPatches aims to have no features that require the mod on both the client and server.
Unless there's a better solution, I'll simply document this behavior and hope that it's not abused, since it's a pretty niche use case anyway.
