### ISSUE TITLE
ctrl-t always toggles narrator, even if "toggle narrator" is unbound

### ISSUE THREAD

**Issue by Scorch-Mechanic** [TheRandomLabs/RandomPatches#91]
Minecraft version: 1.15.2
Mod version: 1.15.2-1.21.1.1
Forge version: 31.1.44
Modpack: "Valhelsia 2", version 2.1.5a

I use the "t" key to throw things, so obviously I use "ctrl-t" to throw whole stacks. 

Unbinding doesn't work. Restarting after unbinding doesn't help either. "Ctrl-b" doesn't activate narrator, so that part's working. It's just there's this errant extra keybinding that does the same thing.

**Comment by AlexProGear** [comment]
Same here, latest mod version for 1.14
Cannot properly use ComputerCraft's "terminate program" feature, because it uses the same combination (ctrl+t)

Edit: so, after searching for suspicious key-related stuff I've found class "RandomPatches/src/main/java/com/therandomlabs/randompatches/patch/client/MinecraftPatch.java"
In here there is a field KEY_UNUSED with value 0x54, which is a keycode of T.
Later in function PatchDispatchKeypresses it's being used under some conditions, which isn't obvious for me
But that should give some hints to devs about solution for this bug

Edit 2: oops, wrong branch. Idk then

**Comment by TheRandomLabs** [comment]
You're right, the key codes are different in LWJGL 3.
